service:
    url: "https://localhost"
    name: "Abrechnung"

database:
    host: "0.0.0.0"
    user: "abrechnung"
    dbname: "abrechnung"

api:
    host: "0.0.0.0"
    base_url: "https://localhost"
    port: 8080
    id: default

registration:
    enabled: false

email:
    host: "localhost"
    port: 587
    mode: "smtp-starttls"
